 function boardMatrix = getNewCheckerboard(boardSize,backgroundIntensity,noiseStdv,noiseStream)
    boardMatrix = uint8(255*(backgroundIntensity + ...
        noiseStdv * backgroundIntensity * ...
        noiseStream.randn(boardSize)));
end