classdef Fly < clandininlab.sources.Subject

    methods

        function obj = Fly()
            import symphonyui.core.*;
            
            obj.addProperty('time', datestr(now), ...
                'type', PropertyType('char', 'row', 'datestr'), ...
                'description', 'Time the preparation was prepared');
            obj.addProperty('preparation', '', ...
                'type', PropertyType('char', 'row', {'', 'Optic lobe (L)', 'Optic lobe (R)', 'Whole Brain'}), ...
                'isPreferred', false);

            obj.addProperty('indicator1', {}, ...
                'type', PropertyType('cellstr', 'row', {'GCaMP6f','GCaMP6m','ASAP2f'}), ...
                'description', 'Fluorescent indicator # 1');
            obj.addProperty('driver1', {}, ...
                'type', PropertyType('cellstr', 'row', {'L2 (21Dhh)','LC11 (R22H02; R20G06)',...
                'LC17 (R21D03; R65C12)', 'LC18 (R82D11; R92B11)', 'LC26 (VT007747; R85H06)'}), ...
                'description', 'Genetic driver #1');
            
            obj.addProperty('indicator2', {}, ...
                'type', PropertyType('cellstr', 'row', {'GCaMP6f','GCaMP6m','ASAP2f'}), ...
                'description', 'Fluorescent indicator # 2');
            obj.addProperty('driver2', {}, ...
                'type', PropertyType('cellstr', 'row', {'L2 (21Dhh)','LC11 (R22H02; R20G06)',...
                'LC17 (R21D03; R65C12)', 'LC18 (R82D11; R92B11)', 'LC26 (VT007747; R85H06)'}), ...
                'description', 'Genetic driver #2');
            
            obj.addAllowableParentType([]);
        end

    end

end
